# Generated by Django 3.2.9 on 2021-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211108_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='preview_image',
            field=models.CharField(default='avb', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='results',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='role',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech_stack',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
    ]
