# Generated by Django 3.2.9 on 2021-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211108_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
